126 enhancement suggestion turn off cell type clustering if bulk tissue
ejh243/BrainFANS pull request #151
Opened 2024-06-10 19:48 UTC by ejh243

# Description

This pull request will make the cell type clustering check optional. To achieve this I have merged the two QC reports into one, with the second one now an optional chunk based on the `ctCheck` variable in the R config file. Had to move some other code sections around and reorder the commands in the job submission script. 

## Issue ticket number

This pull request is to address issue: #126.

## Type of pull request

- [ ] Bug fix
- [X ] New feature/enhancement
- [X] Code refactor
- [ ] Documentation update

## Checklist

- [X ] I have performed a self-review of my own code
- [X ] I have commented my code, particularly in hard-to-understand areas
- [X ] I have tested my code to check that it is functional
- [ ] I have used linters to check for common sources of errors
- [ ] I have implemented fail safes in my code to account for edge cases
- [ ] I have made the corresponding changes to the documentation

2024-06-12 09:05 UTC, ew367 commented
@ejh243 Has this code been tested on any of the devData datasets yet? Is there any example output for the new combined QC report anywhere?

2024-06-12 09:59 UTC, ejh243 commented
YEs I have tested it on my local copy of devData. I will send you the report output

2024-06-14 16:04 UTC, ew367 commented on array/DNAm/preprocessing/rmarkdownChild/ctCheck.rmd
> -args<-commandArgs(trailingOnly = TRUE)
first chunk name 'setup' is duplicate of QC.rmd chunk name so causes error/crash

2024-06-14 17:09 UTC, ew367 requested changes

2024-06-14 17:09 UTC, ew367 commented on array/DNAm/preprocessing/QC.rmd
The example config file in this PR has "tissueType<-"FANS sorted post-mortem brain tissue"
It needs to be "blood" or "brain" as it is used by cetygo to call the correct reference panel

2024-07-05 14:23 UTC, ejh243 commented
@ew367 all changes made and tested with both ctCheck = to TRUE and FALSE, can you re-review?

2024-07-10 12:27 UTC, ew367 approved these changes
re-tested in devData with ctCheck=T and ctCheck=F and works fine on both

2024-07-10 12:28 UTC, merged