add missing libraries and correct bug
ejh243/BrainFANS pull request #222
Opened 2024-09-23 13:23 UTC by ew367

# Description

This pull request will update the installLibraries.r script to add in missing packages needed to run QC.rmd and fix bugs to specify packager installer for V2 arrays and to install remotes:: package to allow install from github repos

## Issue ticket number

This pull request is to address issue: #221

## Type of pull request

- [x] Bug fix
- [ ] New feature/enhancement
- [ ] Code refactor
- [ ] Documentation update

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have tested my code to check that it is functional
- [ ] I have used linters to check for common sources of errors
- [ ] I have implemented fail safes in my code to account for edge cases
- [ ] I have made the corresponding changes to the documentation

2024-09-23 14:01 UTC, sof202 requested changes

2024-09-23 14:03 UTC, sof202 commented on array/DNAm/preprocessing/installLibraries.r
> +pkgs_rep <- c("pander","kableExtra", "gplots", "diptest", "corrplot", "pheatmap", "mixtools")
We also use `reshape2` in the CETYGOdeconvolution.r script

2024-09-23 14:05 UTC, sof202 commented on array/DNAm/preprocessing/installLibraries.r
> +pkgs_rep <- c("pander","kableExtra", "gplots", "diptest", "corrplot", "pheatmap", "mixtools")
We are also relying on the `rmarkdown` library to generate the QC.html report.

https://github.com/ejh243/BrainFANS/blob/8e6dee660c58ac7bacabc7d97af48fcbb2325fd0/array/DNAm/preprocessing/jobSubmission/1_runDNAmQC.sh#L57

2024-09-23 14:06 UTC, sof202 commented on array/DNAm/preprocessing/installLibraries.r
> +pkgs_rep <- c("pander","kableExtra", "gplots", "diptest", "corrplot", "pheatmap", "mixtools")
And add `knitr` to the list as well (though `knitr` might just come with `rmarkdown` or `pander` already)

2024-09-23 14:08 UTC, sof202 commented on array/DNAm/preprocessing/installLibraries.r
> +pkgs_rep <- c("pander","kableExtra", "gplots", "diptest", "corrplot", "pheatmap", "mixtools")
Installing `rmarkdown` will also cover `knitr` as `knitr` is a dependency of the package

2024-09-25 08:09 UTC, sof202 commented on array/DNAm/preprocessing/installLibraries.r
> +	BiocManager::install("jokergoo/IlluminaHumanMethylationEPICv2manifest")
I had a look through the commit history and `library(BiocManager)` has never been used in this file. The lines must have just been copied and pasted in.

2024-09-25 10:07 UTC, ew367 commented
> Also, I presume that this installation script is purely for the 'preprocessing' part of the DNAm pipeline?

Yup

2024-09-25 10:11 UTC, ew367 commented
> You have CRLF (windows line endings) in the new version of the file. Could you change this back to LF (unix line endings)?

done

2024-09-25 10:11 UTC, ew367 commented
> You have CRLF (windows line endings) in the new version of the file. Could you change this back to LF (unix line endings)?

Done

2024-09-25 10:12 UTC, ew367 commented on array/DNAm/preprocessing/installLibraries.r
> +pkgs_rep <- c("pander","kableExtra", "gplots", "diptest", "corrplot", "pheatmap", "mixtools")
Good point. I've added these in

2024-09-25 10:14 UTC, sof202 approved these changes
Cool. We could also use `setdiff` with the `BiocManager::install` calls, but I'll leave that for a different PR.

2024-09-25 10:16 UTC, merged