Try to fix issue 198 - if uniqueIDs is a character, convert to a data frame
ejh243/BrainFANS pull request #263
Opened 2024-11-25 16:50 UTC by bethan-mallabar-rimmer

# Description

In clusterCellTypes.r under 'Calculate individual FACS score' check if uniqueIDs is a character vector - if so convert it to a data frame. This stops uniqueIDs$Individual_ID <- as.character(uniqueIDs$Individual_ID) from breaking as $Individual_ID won't work on a character vector.

This pull request is to address issue: #198 

## Type of pull request

- [x] Bug fix
- [ ] New feature/enhancement
- [ ] Code refactor
- [ ] Documentation update

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have tested my code to check that it is functional
- [ ] I have used linters to check for common sources of errors
- [x] I have implemented fail safes in my code to account for edge cases _(note: it only converts uniqueID$Individual_ID to a dataframe if uniqueID is a character, which would be caused by QCmetrics lacking the Age, Sex, Phenotype, and Tissue.Centre columns. The code also works if QCmetrics contains no columns whatsoever. **The code breaks if QCmetrics contains only the Individual_ID columns and no other columns - as I haven't used BrainFANS can someone let me know if this would ever actually happen?)**_
- [ ] I have made the corresponding changes to the documentation

2024-11-25 17:02 UTC, sof202 commented
I guess to avoid the problem:

> The code breaks if QCmetrics contains only the Individual_ID columns and no other column...

We could just use `if (!is.data.frame(object)) { ...` instead of checking a specific type.

2024-11-25 17:15 UTC, bethan-mallabar-rimmer commented
> I guess to avoid the problem:
> 
> > The code breaks if QCmetrics contains only the Individual_ID columns and no other column...
> 
> We could just use `if (!is.data.frame(object)) { ...` instead of checking a specific type.

Actually nevermind, the code does work if you input a data frame with the Individual_ID column and no other column.
It's just that when you have a data frame with only one column, R has a tendency to convert it to a vector, and this is what caused it to break on my end. If QCmetrics is a vector, then the line `keepCols<-keepCols[keepCols %in% colnames(QCmetrics)]` results in the error `Error in QCmetrics[, keepCols] : incorrect number of dimensions`

If QCmetrics is generated earlier in the BrainFANS pipeline, I'm guessing the chances this object would be a vector rather than a data frame are quite slim?

With that said I prefer your suggestion `if (!is.data.frame(object)) { ...`  because it accounts for other classes that we might want to convert to a dataframe e.g. numeric vectors

2024-11-26 08:26 UTC, ew367 requested changes
Requesting that this be updated to `if (!is.data.frame(object)) { ...` as suggested by @sof202

2024-11-26 12:21 UTC, marinafloresp commented
I agree with comments above. Checking first that the input QCmetrics is a dataframe will avoid later errors.

2024-11-26 16:21 UTC, bethan-mallabar-rimmer commented
> Requesting that this be updated to `if (!is.data.frame(object)) { ...` as suggested by @sof202


> I agree with comments above. Checking first that the input QCmetrics is a dataframe will avoid later errors.

I've now made this change

2024-12-05 15:40 UTC, marinafloresp approved these changes

2024-12-06 11:44 UTC, bethan-mallabar-rimmer commented
@ejh243 Are you able to confirm on your end whether the change I've made addresses your request please, so this pull can be merged and the issue closed? I'm unable to confirm on my end so just guessing that you may be able to. Thanks!

2024-12-11 15:30 UTC, merged